### PR TITLE
Add a simple router with MST

### LINKED ISSUE #1: Add a simple router with MST

### PR DESCRIPTION
**Pull request by DAreRodz**
Closes #1

### CODE REVIEW

**Review by luisherranz — CHANGES_REQUESTED** [review]
Can you add the `now.json` file to this PR?

**Comment by DAreRodz** [comment]
Sure!

**Comment by luisherranz** [comment]
Thanks :)

**Review by luisherranz — APPROVED** [review]

**Comment by luisherranz** [comment]
Awesome! 💪

**Pull request merged**
